#!/bin/bash

# 🌐 Guide pour Obtenir l'IP de votre Serveur ADMINISTRATION.GA

echo "🔍 GUIDE : Comment obtenir l'IP de votre serveur de déploiement"
echo "=============================================================="
echo ""

echo "📋 Méthode 1 : Via votre fournisseur cloud"
echo "----------------------------------------"
echo "• DigitalOcean : Dashboard → Droplets → [Votre serveur] → Adresse IP publique"
echo "• AWS EC2 : Console → Instances → [Votre instance] → IPv4 Public IP"
echo "• Google Cloud : Console → Compute Engine → [Votre VM] → IP externe"
echo "• OVH : Manager → VPS → [Votre VPS] → IP"
echo ""

echo "💻 Méthode 2 : Depuis votre serveur (SSH)"
echo "----------------------------------------"
echo "# Connectez-vous à votre serveur :"
echo "ssh root@[IP_TEMPORAIRE]"
echo ""
echo "# Puis exécutez :"
echo "curl ifconfig.me"
echo "# OU"
echo "curl ipinfo.io/ip"
echo "# OU"
echo "ip addr show | grep 'inet ' | grep -v '127.0.0.1'"
echo ""

echo "🏛️ Méthode 3 : Serveur gouvernemental"
echo "------------------------------------"
echo "• Contactez votre service informatique"
echo "• Demandez l'IP publique du serveur de production"
echo "• Vérifiez les ports ouverts (80, 443, 22)"
echo ""

echo "🧪 Méthode 4 : Test depuis votre machine locale"
echo "----------------------------------------------"
echo "# Si vous développez en local pour tester :"
echo "curl ifconfig.me  # Votre IP publique actuelle"
echo "ifconfig | grep 'inet ' | grep -v '127.0.0.1'  # IP locale"
echo ""

echo "⚠️  IMPORTANT pour ADMINISTRATION.GA :"
echo "======================================"
echo "• L'IP doit être FIXE (pas dynamique)"
echo "• Ports 80 et 443 OUVERTS"
echo "• Serveur avec Ubuntu 22.04+ recommandé"
echo "• RAM minimum : 2GB"
echo "• Stockage : 20GB minimum"
echo "• Bande passante suffisante pour le trafic gouvernemental"
echo ""

echo "📝 Une fois l'IP obtenue :"
echo "========================="
echo "1. Notez votre IP : ________________"
echo "2. Testez la connectivité : ping [VOTRE_IP]"
echo "3. Saisissez-la dans l'interface ADMINISTRATION.GA"
echo "4. Lancez la configuration domaine"
echo ""

echo "🌍 Recommandations par région :"
echo "==============================="
echo "• 🇬🇦 Gabon : Gabon Telecom, Airtel (local)"
echo "• 🇫🇷 France : OVH, Scaleway (proche, francophone)"
echo "• 🌍 International : DigitalOcean Frankfurt, AWS Ireland"
echo ""

echo "✅ Configuration terminée ! Utilisez cette IP dans :"
echo "http://localhost:3000/admin-web/config/administration.ga"
